export const BOXERS = [
  {
    name: 'Glass Joe',
    country: 'France',
    stamina: 1.0,
    power: 1.0,
    health: 1.0,
    speed: 1.0,
    ranking: 10,
    matches: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    winsByKO: 0
  },
  {
    name: 'Von Kaiser',
    country: 'Germany',
    stamina: 1.2,
    power: 1.2,
    health: 1.0,
    speed: 1.0,
    ranking: 9,
    matches: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    winsByKO: 0
  },
  {
    name: 'Piston Honda',
    country: 'Japan',
    stamina: 1.3,
    power: 1.3,
    health: 1.2,
    speed: 1.0,
    ranking: 8,
    matches: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    winsByKO: 0
  },
  {
    name: 'Don Flamenco',
    country: 'Spain',
    stamina: 1.3,
    power: 1.5,
    health: 1.0,
    speed: 1.2,
    ranking: 7,
    matches: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    winsByKO: 0
  },
  {
    name: 'King Hippo',
    country: 'Hippo Island',
    stamina: 1.0,
    power: 1.6,
    health: 1.8,
    speed: 1.0,
    ranking: 6,
    matches: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    winsByKO: 0
  },
  {
    name: 'Great Tiger',
    country: 'India',
    stamina: 1.4,
    power: 1.0,
    health: 1.0,
    speed: 1.5,
    ranking: 5,
    matches: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    winsByKO: 0
  },
  {
    name: 'Bald Bull',
    country: 'Turkey',
    stamina: 1.5,
    power: 2.0,
    health: 2.0,
    speed: 1.2,
    ranking: 4,
    matches: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    winsByKO: 0
  },
  {
    name: 'Soda Popinski',
    country: 'Russia',
    stamina: 1.0,
    power: 2.0,
    health: 1.5,
    speed: 2.0,
    ranking: 3,
    matches: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    winsByKO: 0
  },
  {
    name: 'Mr. Sandman',
    country: 'USA',
    stamina: 2.0,
    power: 2.0,
    health: 2.0,
    speed: 2.0,
    ranking: 2,
    matches: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    winsByKO: 0
  },
  {
    name: 'Mike Tyson',
    country: 'USA',
    stamina: 2.5,
    power: 2.5,
    health: 2.2,
    speed: 2.5,
    ranking: 1,
    matches: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    winsByKO: 0
  },
];
