function defaultStrategyForRanking(ranking) {
  const max = Math.min(7, 11 - ranking);
  const min = Math.max(1, max - 2);
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

export const BOXERS = [
  {
    name: 'Glass Joe',
    nickName: 'Joe',
    country: 'France',
    stamina: 1.0,
    power: 1.0,
    health: 1.0,
    speed: 1.0,
    ranking: 10,
    matches: 11,
    wins: 0,
    losses: 10,
    draws: 1,
    winsByKO: 0,
    age: 29,
    defaultStrategy: defaultStrategyForRanking(10),
    ruleset: 1,
  },
  {
    name: 'Von Kaiser',
    nickName: 'The Kaiser',
    country: 'Germany',
    stamina: 1.2,
    power: 1.2,
    health: 1.0,
    speed: 1.0,
    ranking: 9,
    matches: 25,
    wins: 3,
    losses: 17,
    draws: 5,
    winsByKO: 0,
    age: 36,
    defaultStrategy: defaultStrategyForRanking(9),
    ruleset: 1,
  },
  {
    name: 'Piston Honda',
    nickName: 'Honda',
    country: 'Japan',
    stamina: 1.3,
    power: 1.3,
    health: 1.2,
    speed: 1.0,
    ranking: 8,
    matches: 11,
    wins: 5,
    losses: 5,
    draws: 1,
    winsByKO: 2,
    age: 23,
    defaultStrategy: defaultStrategyForRanking(8),
    ruleset: 1,
  },
  {
    name: 'Don Flamenco',
    nickName: 'Flam',
    country: 'Spain',
    stamina: 1.3,
    power: 1.5,
    health: 1.0,
    speed: 1.2,
    ranking: 7,
    matches: 16,
    wins: 6,
    losses: 10,
    draws: 0,
    winsByKO: 2,
    age: 27,
    defaultStrategy: defaultStrategyForRanking(7),
    ruleset: 2,
  },
  {
    name: 'King Hippo',
    nickName: 'Hippo',
    country: 'Hippo Island',
    stamina: 1.0,
    power: 1.6,
    health: 1.8,
    speed: 1.0,
    ranking: 6,
    matches: 5,
    wins: 3,
    losses: 2,
    draws: 0,
    winsByKO: 3,
    age: 21,
    defaultStrategy: defaultStrategyForRanking(6),
    ruleset: 2,
  },
  {
    name: 'Great Tiger',
    nickName: 'Tiger',
    country: 'India',
    stamina: 1.4,
    power: 1.0,
    health: 1.0,
    speed: 1.5,
    ranking: 5,
    matches: 33,
    wins: 18,
    losses: 12,
    draws: 3,
    winsByKO: 8,
    age: 32,
    defaultStrategy: defaultStrategyForRanking(5),
    ruleset: 3,
  },
  {
    name: 'Bald Bull',
    nickName: 'The Bull',
    country: 'Turkey',
    stamina: 1.5,
    power: 2.0,
    health: 2.0,
    speed: 1.2,
    ranking: 4,
    matches: 40,
    wins: 30,
    losses: 10,
    draws: 0,
    winsByKO: 12,
    age: 27,
    defaultStrategy: defaultStrategyForRanking(4),
    ruleset: 2,
  },
  {
    name: 'Soda Popinski',
    nickName: 'Soda the drunkie',
    country: 'Russia',
    stamina: 1.0,
    power: 2.0,
    health: 1.5,
    speed: 2.0,
    ranking: 3,
    matches: 42,
    wins: 32,
    losses: 8,
    draws: 2,
    winsByKO: 20,
    age: 37,
    defaultStrategy: defaultStrategyForRanking(3),
    ruleset: 1,
  },
  {
    name: 'Mr. Sandman',
    nickName: 'Sandman',
    country: 'USA',
    stamina: 2.0,
    power: 2.0,
    health: 2.0,
    speed: 2.0,
    ranking: 2,
    matches: 35,
    wins: 30,
    losses: 5,
    draws: 0,
    winsByKO: 29,
    age: 30,
    defaultStrategy: defaultStrategyForRanking(2),
    ruleset: 3,
  },
  {
    name: 'Mike Tyson',
    nickName: 'Iron Mike',
    country: 'USA',
    stamina: 2.5,
    power: 2.5,
    health: 2.2,
    speed: 2.5,
    ranking: 1,
    matches: 37,
    wins: 37,
    losses: 0,
    draws: 0,
    winsByKO: 33,
    age: 23,
    defaultStrategy: defaultStrategyForRanking(1),
    ruleset: 3,
  },
];
