export const ARENAS = [
  { "Name": "Madison Square Garden", "City": "New York", "Country": "USA", "Prestige": 3 },
  { "Name": "MGM Grand Garden Arena", "City": "Las Vegas", "Country": "USA", "Prestige": 3 },
  { "Name": "Barclays Center", "City": "Brooklyn", "Country": "USA", "Prestige": 2 },
  { "Name": "Staples Center", "City": "Los Angeles", "Country": "USA", "Prestige": 3 },
  { "Name": "Caesars Palace Pavilion", "City": "Las Vegas", "Country": "USA", "Prestige": 2 },
  { "Name": "The Forum", "City": "Inglewood", "Country": "USA", "Prestige": 2 },
  { "Name": "United Center", "City": "Chicago", "Country": "USA", "Prestige": 2 },
  { "Name": "Atlantic City Convention Hall", "City": "Atlantic City", "Country": "USA", "Prestige": 1 },
  { "Name": "Echo Arena", "City": "Liverpool", "Country": "UK", "Prestige": 2 },
  { "Name": "O2 Arena", "City": "London", "Country": "UK", "Prestige": 3 },
  { "Name": "Manchester Arena", "City": "Manchester", "Country": "UK", "Prestige": 2 },
  { "Name": "York Hall", "City": "London", "Country": "UK", "Prestige": 1 },
  { "Name": "Mercedes-Benz Arena", "City": "Berlin", "Country": "Germany", "Prestige": 2 },
  { "Name": "Forum di Assago", "City": "Milan", "Country": "Italy", "Prestige": 2 },
  { "Name": "Accor Arena", "City": "Paris", "Country": "France", "Prestige": 3 },
  { "Name": "Palacio de los Deportes", "City": "Madrid", "Country": "Spain", "Prestige": 2 },
  { "Name": "Korakuen Hall", "City": "Tokyo", "Country": "Japan", "Prestige": 2 },
  { "Name": "Ryogoku Kokugikan", "City": "Tokyo", "Country": "Japan", "Prestige": 3 },
  { "Name": "Cotai Arena", "City": "Macau", "Country": "China", "Prestige": 2 },
  { "Name": "Mall of Asia Arena", "City": "Pasay", "Country": "Philippines", "Prestige": 2 },
  { "Name": "Lumpinee Boxing Stadium", "City": "Bangkok", "Country": "Thailand", "Prestige": 2 },
  { "Name": "Rajadamnern Stadium", "City": "Bangkok", "Country": "Thailand", "Prestige": 2 },
  { "Name": "FNB Stadium", "City": "Johannesburg", "Country": "South Africa", "Prestige": 3 },
  { "Name": "Cape Town Boxing Hall", "City": "Cape Town", "Country": "South Africa", "Prestige": 1 },
  { "Name": "Accra Sports Stadium", "City": "Accra", "Country": "Ghana", "Prestige": 1 },
  { "Name": "Sydney Super Dome", "City": "Sydney", "Country": "Australia", "Prestige": 3 },
  { "Name": "Kronos Arena", "City": "Athens", "Country": "Greece", "Prestige": 1 },
  { "Name": "Nordic Fight Forum", "City": "Stockholm", "Country": "Sweden", "Prestige": 2 },
  { "Name": "Arctic Boxing Hall", "City": "Reykjavik", "Country": "Iceland", "Prestige": 1 },
  { "Name": "Sahara Boxing Coliseum", "City": "Marrakech", "Country": "Morocco", "Prestige": 1 }
];
